### PR TITLE
Add conditional for dotenv usage

### PR DESCRIPTION
**Pull request by shamsup**
Only load dotenv if the environment variables aren't already set.

### CODE REVIEW

**Review by carsontmoore — APPROVED** [review]
Looks good

**Comment by gilbert** [comment]
I think dotenv prioritizes environment variables over the `.env` file. You could opt to skip it in production, though.

**Comment by shamsup** [comment]
Yea, I just opted to ignore loading the module if the variables are already set because our `.env` file is gitignored. I figured it would be simpler to write the conditional than to try to add the file to one repo and keep it out of another

**Comment by shamsup** [comment]
Well the actual `.env` file is ignored, and we don't really want it to show
up in any repo, so I opted to set the environment variables in heroku
instead.

**Pull request merged**
